import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

esbuild
	.build({
		banner: { js: banner },
		entryPoints: ["src/main.ts"],
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/view",
			"@lezer/common",
			"@lezer/highlight",
			"@lezer/lr",
			// Filter out Node builtins that we need bundled for mobile:
			// buffer, stream, process, events, util, path, crypto — used by isomorphic-git
			...builtins.filter(
				(m) =>
					![
						"buffer",
						"stream",
						"process",
						"events",
						"util",
						"path",
						"crypto",
						"assert",
						"http",
						"https",
						"zlib",
						"fs",
					].includes(m)
			),
		],
		// Provide polyfills for Node builtins used by isomorphic-git on mobile
		inject: [],
		define: {
			"process.env.NODE_ENV": prod ? '"production"' : '"development"',
			global: "globalThis",
		},
		alias: {
			"fs": "./src/shims/fs-shim.ts",
		},
		format: "cjs",
		target: "es2018",
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		outfile: "main.js",
		minify: prod,
	})
	.catch(() => process.exit(1));
